### ISSUE TITLE
Is there any quickstart or sample?

### ISSUE THREAD

**Issue by hexoul** [soohoio/sooho#2]
For starting this repo, README is not enough.
Is there any quickstart or sample?
Although I installed `sooho`, there is nothing to do, except `sooho/cli encrypt`

**Comment by KOREAN139** [comment]
Since `sooho audit` is still in progress (currently it's demo for Devstamp as you can see in this [PR](https://github.com/soohoio/sooho/pull/1)), its doc isn't enough for now. Sorry for inconvenience 😓
You can run `sooho audit INPUT_PATH` to audit your project in `INPUT_PATH`, and sooho cli will print out vulnerabilities in your solidity project if any.
Also you can check [audit.ts](https://github.com/soohoio/sooho/blob/develop/packages/sooho-cli/src/commands/audit.ts) to see how it's working.

**Comment by JisuPark** [comment]
@hexoul Sorry for the late reply.

[@sooho/cli](https://www.npmjs.com/package/@sooho/cli) supports `audit` from the version `v0.3.3` which published seconds ago. Thus the version you tried (v0.3.1) didn't work. We forgot to publish. Sorry for the inconvenience. Please try with the newer version.

Here is the test file: [Vulnerable.sol](https://github.com/soohoio/sooho/blob/develop/packages/sooho-cli/test/commands/Vulnerable.sol)

```
$ sooho audit ./Vulnerable.sol
```

And if you want to build from scratch, you should link libraries through `lerna bootstrap.`
We'll cover instructions as soon as possible.

Thanks,
Jisu

**Comment by hexoul** [comment]
Cool. It works! Thank to @KOREAN139 @JisuPark
